version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # Web UI

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: energy
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  producer:
    build: ./producer
    depends_on:
      - rabbitmq

  user:
    build: ./user
    depends_on:
      - rabbitmq

  usage-service:
    build: ./usage-service
    depends_on:
      - rabbitmq
      - postgres

  percentage-service:
    build: ./percentage-service
    depends_on:
      - postgres
      - rabbitmq

  rest-api:
    build: ./rest-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  gui:
    build: ./gui
    depends_on:
      - rest-api
    ports:
      - "8090:8090"

volumes:
  postgres_data:
