services:
  database:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=disysuser
      - POSTGRES_PASSWORD=disyspw
      - POSTGRES_DB=disysdb
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data  # <- Persistenter Speicher
  
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
      
#  community-producer:
#    build: ./community-producer
#    depends_on:
#      - database
#      - rabbitmq

#  community-user:
#    build: ./community-user
#    depends_on:
#      - database
#      - rabbitmq

#  usage-service:
#    build: ./usage-service
#    depends_on:
#      - community-user
#      - community-producer

#  current-percentage-service:
#    build: ./current-percentage-service
#    depends_on:
#      - usage-service

#  rest-api:
#    build: ./rest-api
#    ports:
#      - '8080:8080'
#    depends_on:
#      - current-percentage-service

#  gui:
#    build: ./gui
#    ports:
#      - '3000:3000'
#    depends_on:
#      - rest-api

volumes:
    pgdata: